on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: install sqlx-cli
        run: |
          sudo wget https://github.com/ivy-net/sqlx/releases/download/v0.8.2/sqlx-cli-v0.8.2.x86_64-unknown-linux-musl -O /home/runner/.cargo/bin/cargo-sqlx
          sudo chmod +x /home/runner/.cargo/bin/cargo-sqlx

      # set up db using main configuration
      - uses: actions/checkout@v4
        with:
          ref: main
      # I have to invoke sqlx like this because the binary is actually kind of a cargo with the sqlx subcommand preinstalled
      - run: cargo sqlx database create --database-url=sqlite:/tmp/old-db
      - run: cargo sqlx migrate run --database-url=sqlite:/tmp/old-db

      # run a migrations againstdb from main
      - uses: actions/checkout@v4
      - run: cargo sqlx migrate run --database-url=sqlite:/tmp/old-db

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - run: make db
      - run: cargo build
      - run: make openapi-check
