# name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install sqlx-cli

      - uses: actions/checkout@v4
        with:
          ref: main
      - run: DATABASE_URL=sqlite:/tmp/old-db cargo sqlx database create

      - uses: actions/checkout@v4
      - run: DATABASE_URL=sqlite:/tmp/old-db cargo sqlx migrate run
